[Feature]  - Controllers
NicolasFujisawa/fatec-lab-dev-5 pull request #29
Opened 2021-02-28 16:55 UTC by toledompm

2021-02-28 17:50 UTC, NicolasFujisawa requested changes

2021-02-28 17:50 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/user/controller/v1/UserController.java
> +                .status(HttpStatus.FOUND)
Seria melhor usar HttpStatus.OK para devolver um correspondente da request.

2021-02-28 17:50 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/user/controller/v1/request/CreateUserRequest.java
> +public class CreateUserRequest {
Pode manter como UserRequest, podemos usar isso para o update.

2021-03-01 01:33 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/option/controller/v1/response/OptionResponse.java
> +    private Set<UserResponse> votes;
Não precisamos dos dados do users aqui, ficaria muito custoso para escalar. Podemos devolver apenas os ids deles, e se precisar dos dados de alguém usamos endpoint.

2021-03-01 01:34 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/option/controller/v1/response/OptionResponse.java
> +}
Criar um campo count para o total de votos.

2021-03-01 01:35 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/poll/controller/v1/converter/PollConverter.java
> +                           )
Não precisa do dado do owner aqui, apenas o id está ok.

2021-03-01 01:36 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/poll/controller/v1/request/PollRequest.java
> +    private User owner;
Não podemos receber um owner aqui, não está persistido. Receber apenas os id, e fazer a busca no service

2021-03-01 01:37 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/poll/controller/v1/response/PollResponse.java
> +    private UserResponse owner;
Não precisamos dos dados do owner aqui, devolver apenas o id.

2021-03-01 01:40 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/option/controller/v1/converter/OptionConverter.java
> +        List<OptionResponse> optionResponses = new LinkedList<>();
= new ArrayList() aqui, é pior pra dar remove, mas pra get é bem mais eficiente.

2021-03-01 01:40 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/user/controller/v1/request/UserRequest.java
> +    private UserRole role;
Remover este campo, pois já temos um valor padrão para ele.

2021-03-01 01:45 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/user/controller/v1/request/UserRequest.java
> +    private UserRole role;
Não sei pqe não ta funcionando as linhas amarelas, mas é o campo role

2021-03-01 11:47 UTC, toledompm commented on src/main/java/fatec/labdev/projeto/pollingapp/poll/controller/v1/request/PollRequest.java
> +    private User owner;
Da pra passar só o Id do owner:
```bash
{
   ...
   "owner": { "id": UUID }
}
```

Deixei dessa forma pq não sei como o repository vai se comportar se só passar o UUID direto.

2021-03-01 11:50 UTC, toledompm commented on src/main/java/fatec/labdev/projeto/pollingapp/user/controller/v1/request/UserRequest.java
> +    private UserRole role;
O construtor com valor Default ta ai pra não precisar mandar a ```role```, mas se a gente quiser ainda pode, deixei assim por isso.

2021-03-01 11:51 UTC, toledompm commented on src/main/java/fatec/labdev/projeto/pollingapp/option/controller/v1/response/OptionResponse.java
> +    private Set<UserResponse> votes;
Vou criar um ```VoteResponse``` que só vai ter o Id do user.

2021-03-01 14:28 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/user/controller/v1/request/UserRequest.java
> +    private UserRole role;
É que se eu não me engano, ele não chega a considerar o campo role. (Se eu mandar ADMIN não vai mudar nada) por causa do construtor, por isso achei que era algo redundante

2021-03-01 15:42 UTC, toledompm commented on src/main/java/fatec/labdev/projeto/pollingapp/user/controller/v1/request/UserRequest.java
> +    private UserRole role;
Ah, o construtor com todos argumentos já ta incluso no ```@Data```. Vou parar de usar essa notation pro projeto ficar mais consistente (e ficar mais fácil de entender)

https://projectlombok.org/features/Data

2021-03-01 15:50 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/user/controller/v1/request/UserRequest.java
> +    private UserRole role;
Verdade, o padrão é para criar user com pass e username, me confundi

2021-03-04 23:38 UTC, jasondavindev commented on src/main/java/fatec/labdev/projeto/pollingapp/option/controller/v1/OptionController.java
> +                .status(HttpStatus.OK)
status created

2021-03-04 23:38 UTC, jasondavindev commented on src/main/java/fatec/labdev/projeto/pollingapp/option/controller/v1/OptionController.java
> +                .status(HttpStatus.OK)
mesma coisa pro resto

2021-03-04 23:39 UTC, jasondavindev commented on src/main/java/fatec/labdev/projeto/pollingapp/option/controller/v1/OptionController.java
> +@RequestMapping("/option")
Se tu criou a pasta v1 pro versionamento, adiciona o v1 na rota também

2021-03-04 23:45 UTC, jasondavindev approved these changes
São detalhes adicionais. Mas o resto tá show :rocket:

2021-03-04 23:45 UTC, jasondavindev commented
As alterações que pedi serve pra todas as classes que tu mexeu

2021-03-05 00:14 UTC, merged

2021-03-05 00:15 UTC, toledompm commented
closes #1