Auth Jwt e end-point Sign In
NicolasFujisawa/fatec-lab-dev-5 pull request #33
Opened 2021-03-27 01:05 UTC by NicolasFujisawa

#22

2021-04-08 21:07 UTC, toledompm approved these changes
LGTM

2021-04-08 21:07 UTC, toledompm commented on src/main/java/fatec/labdev/projeto/pollingapp/config/global/WebSecurityConfig.java
> +    };
:question:
O que que seriam esses antPatterns :sweat_smile:

2021-04-08 21:07 UTC, toledompm commented on src/main/java/fatec/labdev/projeto/pollingapp/config/global/WebSecurityConfig.java
> +        http.addFilterBefore(jwtRequestFilter, UsernamePasswordAuthenticationFilter.class);
Isso aqui ta ficando meio feio né :s

2021-04-08 21:07 UTC, toledompm commented on src/main/java/fatec/labdev/projeto/pollingapp/config/jwt/JwtAuthenticationEntryPoint.java
> +}
:question:
Esse component tbm é meio novo pra mim, tem uma explicação basicona?

2021-04-08 21:07 UTC, toledompm commented on src/main/java/fatec/labdev/projeto/pollingapp/config/jwt/JwtRequestFilter.java
> +        filterChain.doFilter(request, response);
Faz sentido algum log/retorno se a validação falhar?

2021-04-08 21:07 UTC, toledompm commented on src/main/java/fatec/labdev/projeto/pollingapp/user/service/UserServiceImpl.java
> +    private PasswordEncoder passwordEncoder;
:rocket:

2021-04-08 21:11 UTC, toledompm commented
Esse PR fecha essas 3 issues certo?
#21 #22 #23

Ou tem algo em alguma que ainda vai faltar fazer?

2021-04-08 21:20 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/config/jwt/JwtAuthenticationEntryPoint.java
> +}
É um Bean basicamente, como um Service, Controller, Repository, mas com nome de component

2021-04-08 21:22 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/config/global/WebSecurityConfig.java
> +    };
Vou mudar esse nome, mas são os endpoints não protegidos (sem Jwt auth)

2021-04-08 22:58 UTC, jasondavindev requested changes

2021-04-08 22:58 UTC, jasondavindev commented on src/main/java/fatec/labdev/projeto/pollingapp/config/jwt/JwtRequestFilter.java
> +        }
Isso deveria estar em outro método

2021-04-08 22:58 UTC, jasondavindev commented on src/main/java/fatec/labdev/projeto/pollingapp/config/global/WebSecurityConfig.java
> +    private static final String[] antPatterns = new String[]{
```suggestion
    private static final String[] unguardRoutes = new String[]{
```

2021-04-08 22:58 UTC, jasondavindev commented on src/main/java/fatec/labdev/projeto/pollingapp/config/jwt/JwtRequestFilter.java
> +        }
Isso também deveria estar em outro método.
Tem um padrão que esqueci o nome que primeiro trata o caso que não tem fluxo, ex `username == null`. Isso evita processamento desnecessário e torna o código mais legível.

2021-04-08 22:58 UTC, jasondavindev commented on src/main/java/fatec/labdev/projeto/pollingapp/user/service/UserDetailsServiceImpl.java
> +        User user = this.userService.findByUsername(username);
Isso aqui gera duas queries desnecessárias. Com uma só resolve, mas tá ok.

2021-04-08 22:58 UTC, jasondavindev commented on src/main/java/fatec/labdev/projeto/pollingapp/user/service/UserServiceImpl.java
> +        user.setPassword(this.passwordEncoder.encode(user.getPassword()));
Isso aqui vai encodar toda vez que rodar um save?

2021-04-08 23:08 UTC, toledompm commented on src/main/java/fatec/labdev/projeto/pollingapp/config/jwt/JwtRequestFilter.java
> +        }
esse né?
https://medium.com/swlh/return-early-pattern-3d18a41bba8

2021-04-08 23:44 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/user/service/UserServiceImpl.java
> +        user.setPassword(this.passwordEncoder.encode(user.getPassword()));
Isso mesmo

2021-04-09 01:21 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/config/global/WebSecurityConfig.java
> +        http.addFilterBefore(jwtRequestFilter, UsernamePasswordAuthenticationFilter.class);
Acredito que seja só isso que precisamos (a longo prazo).

2021-04-09 02:00 UTC, jasondavindev commented on src/main/java/fatec/labdev/projeto/pollingapp/user/service/UserServiceImpl.java
> +        user.setPassword(this.passwordEncoder.encode(user.getPassword()));
Mas se eu mandar um update no usuário só pra atualizar uma campo aleatorio, ele vai mudar a senha. Tá certo isso?

2021-04-09 02:02 UTC, jasondavindev approved these changes

2021-04-09 02:10 UTC, NicolasFujisawa commented on src/main/java/fatec/labdev/projeto/pollingapp/user/service/UserServiceImpl.java
> +        user.setPassword(this.passwordEncoder.encode(user.getPassword()));
o PUT tem que enviar todos os campos, se quiser atualizar só um campo teria que usar o PATCH

2021-04-09 02:10 UTC, merged